export const announcements = [
    {
        id: 'pengumuman-dan-rangkuman-pertemuan-perdana-kelompok-peru',
        title: 'Pengumuman dan Rangkuman Pertemuan Perdana Kelompok Peru',
        desc: 'Pada hari Minggu tanggal 01 September 2024, Kelompok Peru mengadakan pertemuan untuk membahas hal-hal yang berkaitan dengan tugas kelompok Mabim. Untuk detail dari hasil pertemuan silahkan dicek ya!!',
        date: 'Minggu, 01 September 2024',
        time: '13.00 WIB',
        announcements: [
            'IG kelompok adalah @thisisperupride_',
            'Take video tugas kelompok direncanakan dilaksanakan hari Rabu, 4 September 2024 pukul 10.00 di Hutan Damar (Daerah Situ Gunung)',
            'Dresscode anggota perempuan saat take video tugas kelompok yaitu : Kerudung hitam, Baju merah/putih dan Celana/Rok hitam',
            'Dresscode anggota lai-laki saat take video tugas kelompok yaitu : Baju merah/putih dan Celana hitam',
        ],
        summaries: [
            'Perubahan struktur kelompok',
            'IG kelompok adalah @thisisperupride_',
            'IG kelompok bertemakan alam',
            'Tugas video pentas seni adalah nari yang akan dibawakan oleh Intan',
            'Pembuatan Yel-yel kelompok',
            'Pemandu Yel-yel adalah Yovi',
        ],
    },
    {
        id: 'pengumuman-perubahan-rencana-take-video-tugas-kelompok',
        title: 'Pengumuman Perubahan Rencana Take Video Tugas Kelompok',
        desc: 'Pada hari Senin tanggal 02 September 2024, beberapa pengurus inti kelompok Peru mengadakan pertemuan dan membahas hal-hal yang berkaitan dengan rencana take video kelompok. Untuk detail dari hasil pertemuan silahkan dicek ya!!',
        date: 'Senin, 02 September 2024',
        time: '19.00 WIB',
        announcements: [
            'Dresscode take video adalah atasan hitam dan bawahan hitam untuk laki-laki maupun perempuan',
            'Ciri khas kelompok akan dibuat oleh Aulia dan anggota kelompok yang lain hany membayar iuran saja',
            'Tempat take video adalah di Situ Gunung',
            'Titik kumpul sebelum ke Situ Gunung adalah di Alun-Alun Cisaat',
            'Semua anggota hadir di titk kumpul pada pukul 9.30 WIB',
        ],
        summaries: [],
    },
    {
        id: 'pengumuman-mengenai-take-video-tugad-kelompok',
        title: 'Pengumuman Mengenai Take Video Tugas Kelompok',
        desc: 'Pada hari Selasa tanggal 03 September 2024, Ketua Kelompok Peru mengumumkan beberapa hal yang perlu diketahui oleh anggota kelompok. Untuk detail pengumumannya silahkan dicek ya!!',
        date: 'Selasa, 03 September 2024',
        time: '19.00 WIB',
        announcements: [
            'Hari Rabu tanggal 04 September 2024 pukul 10.00 WIB akan diadakan pertemuan kembali',
            'Agenda pertemuan hari Rabu tanggal 04 September 2024 pukul 10.00 WIB adalah take video pentas seni dan yel-yel kelompok',
            'Take video akan dilakukan di Situ Gunung',
            'Titik kumpul sebelum ke Situ Gunung adalah di Alun Alun Cisaat pukul 09.30 WIB',
            'Semua anggota kelompok yang tidak berhalangan diharapkan bisa hadir',
        ],
        summaries: [],
    },
    {
        id: 'pengumuman-dan-rangkuman-progress-video-tugas-kelompok-1',
        title: 'Pengumuman dan Rangkuman Progress Video Tugas Kelompok 1',
        desc: 'Pada hari Rabu tanggal 04 September 2024, Kelompok Peru mengadakan pertemuan yang bertujuan untuk take video tugas kelompok. Untuk detail dari progress video tugas kelompok silahakan dicek ya!!',
        date: 'Rabu, 04 September 2024',
        time: '19.00 WIB',
        announcements: [
            'Editing video tugas kelompok akan dilaksanakan hari Kamis tanggal 05 September di rumah Zalfan',
        ],
        summaries: [
            'Take video pentas seni sudah selesai',
            'Take video yel-yel sudah selesai',
        ],
    },
    {
        id: 'pengumuman-dan-rangkuman-progress-video-tugas-kelompok-2',
        title: 'Pengumuman dan Rangkuman Progress Video Tugas Kelompok 2',
        desc: 'Pada hari Kamis tanggal 05 September 2024, Pubdekdok Kelompok Peru melakukan pertemuan untuk editing video tugas kelompok. Untuk detail progressnya silahkan dicek ya!!',
        date: 'Kamis, 05 September 2024',
        time: '21.00 WIB',
        announcements: [
            `Editing video akan dilanjut hari Jum'at tanggal 06 September 2024 di rumah Zalfan`,
        ],
        summaries: [
            `Progress editing video pentas seni 80%`,
            'Progress editing video yel-yel 40%',
        ],
    },
]

export const members = [
    {
        id: 0,
        name: 'Ridzky Muhammad Anwar',
        role: 'Mentor',
        major: 'Manajemen',
        src: '/img/member/ridzky.png',
        instagram: 'mrdzkynwr_',
    },
    {
        id: 1,
        name: 'Zalfan Adisaki',
        role: 'Ketua',
        major: 'Akutansi',
        src: '/img/member/zalfan.png',
        instagram: 'zalfan_adisaki',
    },
    {
        id: 2,
        name: 'Nur Aulia Sholihah Hasyi',
        role: 'Wakil Ketua',
        major: 'Hukum',
        src: '/img/member/aulia.png',
        instagram: 'nuraauliaash_',
    },
    {
        id: 3,
        name: 'Muhammad Fabian Azhar',
        role: 'Sekretaris',
        major: 'Sistem Informasi',
        src: '/img/member/fabian.jpg',
        instagram: 'fabianazhrr',
    },
    {
        id: 4,
        name: 'Rista Julia Moniq Pratama',
        role: 'Bendahara',
        major: 'PGSD',
        src: '/img/member/rista.png',
        instagram: 'ristaajp',
    },
    {
        id: 5,
        name: 'Zaskia Bulan Pratama',
        role: 'Publish',
        major: 'Teknik Informatika',
        src: '/img/member/zaskia.jpg',
        instagram: 'bull_11',
    },
    {
        id: 6,
        name: 'Dahlia Nurohmawati Putri',
        role: 'Publish',
        major: 'Manajemen',
        src: '/img/member/dahlia.png',
        instagram: 'dahliaaputrii_',
    },
    {
        id: 7,
        name: 'Muhammad Alfarizzi Sutisna',
        role: 'Dokumentasi',
        major: 'Teknik Informatika',
        src: '/img/member/alfarizzi.png',
        instagram: 'pixx.ellx',
    },
    {
        id: 8,
        name: 'Arizal Afsal',
        role: 'Desain',
        major: 'Sistem Informasi',
        src: '/img/member/arizal.png',
        instagram: 'arizalafsl',
    },
    {
        id: 9,
        name: 'Gina Salma',
        role: 'Desain',
        major: 'DKV',
        src: '/img/member/gina.jpg',
        instagram: 'gisa_art736',
    },
    {
        id: 10,
        name: 'Hilmy Khairy Fasya',
        role: 'Keamanan',
        major: 'Manajemen',
        src: '/img/member/hilmy.jpg',
        instagram: 'me_hilmy12',
    },
    {
        id: 11,
        name: 'Ibrahimovic Nur Chandra',
        role: 'Keamanan',
        major: 'Hukum',
        src: '/img/member/ibrahimovic.png',
        instagram: 'movicnurchandra',
    },
    {
        id: 12,
        name: 'Yovi Andri Dwi Nugraha',
        role: 'Keamanan',
        major: 'Teknik Informatika',
        src: '/img/member/yovi.jpg',
        instagram: 'yyopiii_',
    },
    {
        id: 13,
        name: 'Muhamad Yusup',
        role: 'Keamanan',
        major: 'Manajemen',
        src: '/img/member/yusup.png',
        instagram: 'ysfalfrzz',
    },
    {
        id: 14,
        name: 'Zahra Nur Fatimah',
        role: 'Keamanan',
        major: 'Akutansi',
        src: '/img/member/zahra.png',
        instagram: 'zahraanff_',
    },
    {
        id: 15,
        name: 'Audy Auliany',
        role: 'Anggota',
        major: 'Manajemen',
        src: '/img/member/audy.png',
        instagram: 'audiaayn_',
    },
    {
        id: 16,
        name: 'Bunga',
        role: 'Anggota',
        major: 'Manajemen',
        src: '/img/member/bunga.png',
        instagram: 'bungafflr_',
    },
    {
        id: 17,
        name: 'Fajar Danuar Permana',
        role: 'Anggota',
        major: 'Teknik Informatika',
        src: '/img/member/fajar.png',
        instagram: 'fdanuarp',
    },
    {
        id: 18,
        name: 'Fauzan Ferdiansyah',
        role: 'Anggota',
        major: 'Hukum',
        src: '/img/member/fauzan.png',
        instagram: 'fauzanferdiansyah_',
    },
    {
        id: 19,
        name: 'Intan Apriliani',
        role: 'Anggota',
        major: 'Manajemen',
        src: '/img/member/intan.png',
        instagram: 'prilldeee',
    },
    {
        id: 20,
        name: 'Mella Maulia Nursaputri',
        role: 'Anggota',
        major: 'Manajemen',
        src: '/img/member/mella.png',
        instagram: 'Mellamaulia18',
    },
    {
        id: 21,
        name: 'Muhammad Affryansa',
        role: 'Anggota',
        major: 'Manajemen',
        src: '/img/member/affryansa.png',
        instagram: 'Mhaffryansah7',
    },
    {
        id: 22,
        name: 'Muhammad Gilang Al-Bawafi',
        role: 'Anggota',
        major: 'Teknik Sipil',
        src: '/img/member/gilang.png',
        instagram: 'gilang93941',
    },
    {
        id: 23,
        name: 'Muhammad Irman',
        role: 'Anggota',
        major: 'Manajemen',
        src: '/img/member/irman.jpg',
        instagram: 'thereal_pham',
    },
    {
        id: 24,
        name: 'Muhammad Zahran Ramdhani Nurmansyah',
        role: 'Anggota',
        major: 'Teknik Sipil',
        src: '/img/member/zahran.png',
        instagram: 'zahran.rn',
    },
    {
        id: 25,
        name: 'Nabila Fasya Hermawan',
        role: 'Anggota',
        major: 'Manajemen',
        src: '/img/member/nabila.jpg',
        instagram: 'nabilafasyaaf',
    },
    {
        id: 26,
        name: 'Nur Azhmi Octavia',
        role: 'Anggota',
        major: 'Hukum',
        src: '/img/member/azmi.png',
        instagram: 'cheoctavi',
    },
    {
        id: 27,
        name: 'Nurani',
        role: 'Anggota',
        major: 'PGSD',
        src: '/img/member/nurani.png',
        instagram: 'raninr_',
    },
    {
        id: 28,
        name: 'Rusdianto Nugraha',
        role: 'Anggota',
        major: 'Akutansi',
        src: '/img/member/rusdianto.png',
        instagram: 'rusdii_18',
    },
    {
        id: 29,
        name: 'Sabrina Nauran Haq',
        role: 'Anggota',
        major: 'Hukum',
        src: '/img/member/sabrina.png',
        instagram: 'sbinabeen',
    },
    {
        id: 30,
        name: 'Salsabila Devina Salma',
        role: 'Anggota',
        major: 'Teknik Informatika',
        src: '/img/member/salsabila.png',
        instagram: 'salsaabila0',
    },
    {
        id: 31,
        name: 'Siti Liani',
        role: 'Anggota',
        major: 'PGSD',
        src: '/img/member/siti.png',
        instagram: 'sitiliani1',
    },
    {
        id: 32,
        name: 'Diefa Jati Kusumua',
        role: 'Anggota',
        major: 'Teknik Elektro',
        src: '/img/member/diefa.png',
        instagram: 'diefazze',
    },
    {
        id: 33,
        name: 'Iva Nuraeni',
        role: 'Anggota',
        major: 'Teknik Sipil',
        src: '/img/member/iva.png',
        instagram: 'ivnrraa_',
    },
    {
        id: 34,
        name: 'Riswan Maulana',
        role: 'Anggota',
        major: 'Teknik Sipil',
        src: '/img/member/riswan.png',
        instagram: 'riswan4415',
    },
]

export const galleries = [
    {
        id: 'pertemuan-perdana-kelompok-peru',
        title: 'Pertemuan Perdana Kelompok Peru',
        date: '1 September 2024',
        thumbnail: '/img/gallery/1-sep/',
        gdrive: '-',
    },
]
